server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/Widres8/microservicesspring
          search-path: config-data
  application:
    name: config-service
