server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/widres8/microservicesspring
          search-path: config-data
  application:
    name: config-service
